default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nodebucks_development

test:
  <<: *default
  database: nodebucks_test

production:
  <<: *default
  database: nodebucks_production
  username: nodebucks
  password: <%= ENV['NODEBUCKS_DATABASE_PASSWORD'] %>
